services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: malik-seed-backend
    restart: unless-stopped
    ports:
      - "9000:8000"
    env_file:
      - .env
    volumes:
      - ./data/db:/app/data
      - ./data/uploads:/app/uploads
    networks:
      - malik-seed-network

  frontend:
    build:
      context: ./atlantis-ng-21.0.0
      dockerfile: Dockerfile
      args:
        - API_BASE_URL=https://apimalikseed.syscomatic.cloud/api/v1
        - MEDIA_BASE_URL=https://apimalikseed.syscomatic.cloud/
    container_name: malik-seed-frontend
    restart: unless-stopped
    ports:
      - "6500:80"
    depends_on:
      - backend
    networks:
      - malik-seed-network

networks:
  malik-seed-network:
    driver: bridge
